# Form implementation generated from reading ui file '/Users/valentinaosoriolopez/Library/CloudStorage/OneDrive-UniversidaddelaSabana/UNIVERSIDAD/9 SEMESTRE/Programación Avanzada/ProyectoFinalPA/ProyectoFinalPA/ui/Departamento.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(629, 599)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(20, 240, 591, 51))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Bcrear = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.Bcrear.setStyleSheet("border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(0, 51, 102);\n"
"background-color: rgb(0, 51, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.Bcrear.setObjectName("Bcrear")
        self.horizontalLayout_6.addWidget(self.Bcrear)
        self.Bbuscar = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.Bbuscar.setStyleSheet("border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(0, 51, 102);\n"
"background-color: rgb(0, 51, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.Bbuscar.setObjectName("Bbuscar")
        self.horizontalLayout_6.addWidget(self.Bbuscar)
        self.Beliminar = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.Beliminar.setStyleSheet("border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(0, 51, 102);\n"
"background-color: rgb(0, 51, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.Beliminar.setObjectName("Beliminar")
        self.horizontalLayout_6.addWidget(self.Beliminar)
        self.Bactualizar = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.Bactualizar.setStyleSheet("border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(0, 51, 102);\n"
"background-color: rgb(0, 51, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.Bactualizar.setObjectName("Bactualizar")
        self.horizontalLayout_6.addWidget(self.Bactualizar)
        self.Bregresar = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Bregresar.setFont(font)
        self.Bregresar.setStyleSheet("border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(0, 51, 102);\n"
"background-color: rgb(255, 61, 74);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.Bregresar.setObjectName("Bregresar")
        self.horizontalLayout_6.addWidget(self.Bregresar)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(130, 60, 371, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bodoni 72 Oldstyle")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.Sid = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.Sid.setObjectName("Sid")
        self.horizontalLayout.addWidget(self.Sid)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bodoni 72 Oldstyle")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.Lnombre = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Lnombre.setObjectName("Lnombre")
        self.horizontalLayout_4.addWidget(self.Lnombre)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bodoni 72 Oldstyle")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.Lextension = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Lextension.setObjectName("Lextension")
        self.horizontalLayout_5.addWidget(self.Lextension)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bodoni 72 Oldstyle")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.Cjefe = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.Cjefe.setObjectName("Cjefe")
        self.horizontalLayout_3.addWidget(self.Cjefe)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tabla = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla.setGeometry(QtCore.QRect(20, 300, 591, 251))
        self.tabla.setStyleSheet("background-color: rgb(0, 51, 102, 50);")
        self.tabla.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.tabla.setObjectName("tabla")
        self.tabla.setColumnCount(4)
        self.tabla.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Bodoni 72 Oldstyle")
        item.setFont(font)
        self.tabla.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Bodoni 72 Oldstyle")
        item.setFont(font)
        self.tabla.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Bodoni 72 Oldstyle")
        item.setFont(font)
        self.tabla.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Bodoni 72 Oldstyle")
        item.setFont(font)
        self.tabla.setHorizontalHeaderItem(3, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 611, 56))
        font = QtGui.QFont()
        font.setFamily("Bodoni 72 Oldstyle")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 629, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Departamento"))
        self.Bcrear.setText(_translate("MainWindow", "Crear"))
        self.Bbuscar.setText(_translate("MainWindow", "Buscar"))
        self.Beliminar.setText(_translate("MainWindow", "Eliminar"))
        self.Bactualizar.setText(_translate("MainWindow", "Actualizar"))
        self.Bregresar.setText(_translate("MainWindow", "Regresar"))
        self.label_2.setText(_translate("MainWindow", "Id"))
        self.label_3.setText(_translate("MainWindow", "Nombre"))
        self.label_6.setText(_translate("MainWindow", "Extensión"))
        self.label_5.setText(_translate("MainWindow", "Jefe del Departamento"))
        item = self.tabla.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Codigo"))
        item = self.tabla.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tabla.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Extension"))
        item = self.tabla.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Jefe"))
        self.label.setText(_translate("MainWindow", "Gestión De Departamento"))
