# Form implementation generated from reading ui file 'c:\Users\PERSONAL\Desktop\ProyectoFinalPA\Opciones.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 30, 271, 91))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Bnuevo = QtWidgets.QPushButton(self.centralwidget)
        self.Bnuevo.setGeometry(QtCore.QRect(260, 130, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Bnuevo.setFont(font)
        self.Bnuevo.setObjectName("Bnuevo")
        self.Bbuscar = QtWidgets.QPushButton(self.centralwidget)
        self.Bbuscar.setGeometry(QtCore.QRect(260, 200, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Bbuscar.setFont(font)
        self.Bbuscar.setObjectName("Bbuscar")
        self.Btodos = QtWidgets.QPushButton(self.centralwidget)
        self.Btodos.setGeometry(QtCore.QRect(260, 270, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Btodos.setFont(font)
        self.Btodos.setObjectName("Btodos")
        self.Beliminar = QtWidgets.QPushButton(self.centralwidget)
        self.Beliminar.setGeometry(QtCore.QRect(260, 340, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Beliminar.setFont(font)
        self.Beliminar.setObjectName("Beliminar")
        self.Bactualizar = QtWidgets.QPushButton(self.centralwidget)
        self.Bactualizar.setGeometry(QtCore.QRect(260, 410, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Bactualizar.setFont(font)
        self.Bactualizar.setObjectName("Bactualizar")
        self.Bregresar = QtWidgets.QPushButton(self.centralwidget)
        self.Bregresar.setGeometry(QtCore.QRect(260, 480, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Bregresar.setFont(font)
        self.Bregresar.setObjectName("Bregresar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Opciones"))
        self.label.setText(_translate("MainWindow", "Opciones"))
        self.Bnuevo.setText(_translate("MainWindow", "Nuevo"))
        self.Bbuscar.setText(_translate("MainWindow", "Buscar"))
        self.Btodos.setText(_translate("MainWindow", "VerTodos"))
        self.Beliminar.setText(_translate("MainWindow", "Eliminar"))
        self.Bactualizar.setText(_translate("MainWindow", "Actualizar"))
        self.Bregresar.setText(_translate("MainWindow", "Regrear"))
